import Link from "next/link";

type Guide = { title: string; intent: string; click: string; result: string; next?: string };
type Endpoint = { method: string; path: string; purpose: string; body?: string; response: string };

const guides: Guide[] = [
  { title: "Overview → incident row", intent: "Open an incident from the SOC queue.", click: "Click any incident row, such as INC-1042.", result: "Nexus selects the incident, opens its investigation workspace, and carries the incident ID into the header and tabs.", next: "Click Start / resume to initialize durable investigation records." },
  { title: "Overview → New investigation", intent: "Choose an incident from the launch dialog.", click: "Click New investigation, then select an incident in the modal.", result: "The selected incident becomes active and the Investigation tab opens. The API creates the investigation if it does not already exist." },
  { title: "Overview → global search", intent: "Filter the active incident queue.", click: "Type an ID, title, host, or user in Search incidents.", result: "Rows are filtered immediately in the browser. No server mutation occurs." },
  { title: "Overview → Next best action", intent: "Understand the recommended next investigation action.", click: "Click Open investigation.", result: "Nexus opens the selected incident workspace. The card explains why the action is recommended and lists the configured source systems required." },
  { title: "Investigations → Start / resume", intent: "Create or resume the durable case.", click: "Click Start / resume.", result: "POST /api/investigations initializes the Prisma investigation, 14 steps, evidence records, and normalized timeline. The UI then opens the Investigation tab." },
  { title: "Investigation tab → step check", intent: "Record analyst progress.", click: "Click the numbered circle or checkmark beside a step.", result: "The step is marked complete or reopened locally, then PATCH /api/investigations/:id/steps persists the state and creates audit/replay events. The progress bar updates." },
  { title: "Investigation tab → Open tool", intent: "Jump from a pending step to the correct workspace.", click: "Click Open tool on a pending step.", result: "Network, identity, and threat-intelligence steps open Queries; other collection steps open Artifacts. The recommendation identifies the configured source." },
  { title: "Investigation tab → Open evidence vault", intent: "Review collection completeness.", click: "Click Open evidence vault.", result: "The Evidence tab shows all 12 required records, source provenance, collection time, confidence, and unresolved artifacts." },
  { title: "Timeline tab → event row", intent: "Inspect one normalized event.", click: "Click any timeline event.", result: "The right panel shows source, host, user, timestamp, description, and whether the relationship is observed or only potential." },
  { title: "Timeline tab → Export timeline", intent: "Copy the event sequence into a case note.", click: "Click Export timeline.", result: "The normalized timeline is copied to the clipboard. No evidence is changed." },
  { title: "Artifacts/Evidence → Collect available evidence", intent: "Refresh evidence from configured adapters.", click: "Click Collect available evidence.", result: "The API returns collected and missing records and records an evidence collection audit event. Current live sources remain synthetic unless configured." },
  { title: "Artifacts/Evidence → artifact chevron", intent: "Open evidence provenance.", click: "Click the chevron on an artifact row.", result: "A modal shows the value, source tool, confidence, event reference, and raw reference. Pending artifacts remain visibly unresolved." },
  { title: "Queries → platform choice", intent: "Choose the query syntax to generate.", click: "Click Splunk, Google SecOps, CrowdStrike Falcon, Palo Alto, or Sentinel.", result: "The selected deterministic template changes. Disabled platforms are unavailable because the client environment does not have that tool enabled." },
  { title: "Queries → indicator", intent: "Set the pivot value.", click: "Edit the Indicator field with an IP, hash, hostname, or user.", result: "The value is parameterized into the selected template; it is not sent to an external platform in mock mode." },
  { title: "Queries → Run mock query", intent: "Execute a safe synthetic search.", click: "Click Run mock query.", result: "POST /api/queries/run stores the generated query and execution audit record, then returns normalized synthetic timeline results." },
  { title: "Queries → Copy query", intent: "Use the generated query in an approved external workflow.", click: "Click Copy query.", result: "The exact deterministic query is copied. Nexus does not execute a real platform action." },
  { title: "Queries → Save to library", intent: "Keep the current query in the local query history.", click: "Click Save to library.", result: "The query is saved to browser history for the current demo workspace." },
  { title: "Analysis → Summary editor", intent: "Write analyst-owned findings.", click: "Type or paste into Summary, Technical Findings, Scope, or Recommended Actions.", result: "The original analyst text stays under analyst control. Editing clears the applied-correction state so QA must be reviewed again." },
  { title: "Analysis → Use evidence value", intent: "Resolve a detected mismatch with explicit approval.", click: "Click Use evidence value on the hostname warning.", result: "Only the displayed hostname correction is applied to the draft. The analyst must still review the rest of the text." },
  { title: "Analysis → Keep analyst value", intent: "Preserve an intentional analyst value.", click: "Click Keep analyst value.", result: "The original value remains. The warning is treated as reviewed, not silently deleted from the audit context." },
  { title: "Analysis → Apply wording suggestion", intent: "Use evidence-aligned terminology.", click: "Click Apply wording suggestion in Security Analysis QA.", result: "The word malicious is changed to potentially malicious in the draft. The suggestion is deterministic and reviewable." },
  { title: "Analysis → Fix & proofread", intent: "Apply the current safe corrections.", click: "Click Fix & proofread.", result: "The draft is updated with the reviewed hostname and safer terminology. A subsequent QA run should be used before submission." },
  { title: "Report → Copy report", intent: "Move a draft into a ticket or review note.", click: "Click Copy report.", result: "The current report text, findings, and timeline are copied to the clipboard." },
  { title: "Report → Export PDF", intent: "Create a reviewable document locally.", click: "Click Export PDF.", result: "The browser print dialog opens. Choose Save as PDF. Production signed PDF generation is a remaining deployment integration." },
  { title: "Report → Create ticket", intent: "Prepare a ticket without transmitting it.", click: "Click Create ticket, fill the draft, then Save local draft.", result: "A local ServiceNow-shaped draft is created. No external ticket is sent without a configured integration and human approval." },
  { title: "Report → Generate handoff", intent: "Transfer the case between analysts.", click: "Click Generate handoff.", result: "The modal summarizes completed and pending steps, key findings, missing evidence, next action, queries, and collected evidence. Copy Handoff copies it." },
  { title: "Environments → tool toggle", intent: "Change which tools Nexus may recommend or query.", click: "Click a tool switch, then Save environment.", result: "The selection persists in the browser and changes available query platforms, source tags, and next-action recommendations. Live credentials are not created by this toggle." },
  { title: "Environments → Save environment", intent: "Persist client tool enablement for server-side consumers.", click: "Click Save environment after changing switches.", result: "The client tool enablement is sent to POST /api/environment/save and stored in Prisma. The UI confirms whether the server accepted the change." },
  { title: "Dashboard metrics", intent: "Read current persisted case counts.", click: "Open Overview.", result: "Dashboard count APIs are available through GET /api/dashboard. The current presentation keeps the polished demo metric treatment while server counts are now available for the next UI refresh pass." },
  { title: "Analysis → Save draft", intent: "Persist the complete analyst draft.", click: "Click Save draft in the Analysis tab.", result: "The summary, technical findings, scope, and recommended actions are saved to Prisma and a replay/audit event is written." },
  { title: "API & Docs → OpenAPI spec", intent: "Inspect machine-readable API contracts.", click: "Click OpenAPI spec.", result: "A new tab opens /api/openapi with the route catalogue and request schema examples." },
  { title: "Progress & Roadmap", intent: "See what is implemented versus operationally pending.", click: "Click Progress & Roadmap in the sidebar.", result: "The completed lane shows the working demo and architecture. The remaining lane names live integrations, SSO, real AI clients, test automation, and operations work." },
  { title: "Top bar → activity", intent: "Jump to delivery tracking.", click: "Click the activity icon.", result: "Progress & Roadmap opens." },
  { title: "Top bar → help", intent: "Open documentation from anywhere.", click: "Click the question-mark icon.", result: "The in-app API & Docs section opens." },
  { title: "Mobile menu", intent: "Navigate on a narrow viewport.", click: "Click the menu icon, then a sidebar destination.", result: "The drawer opens over the page; selecting a destination closes it." },
];

const endpoints: Endpoint[] = [
  { method: "GET", path: "/api/health", purpose: "Reports service mode and timestamp.", response: "{ status, mode, externalIntegrations, timestamp }" },
  { method: "GET", path: "/api/ready", purpose: "Checks database readiness for traffic routing.", response: "200 ready or 503 not_ready." },
  { method: "GET", path: "/api/metrics", purpose: "Returns persisted record counts and process metadata for operations.", response: "incidents, investigations, evidence, auditEvents, process." },
  { method: "GET", path: "/api/analytics/sla", purpose: "Calculates triage and investigation-to-report intervals from persisted audit events.", response: "Measured cases, targetMinutes, and explicit telemetry caveat." },
  { method: "GET", path: "/api/session", purpose: "Returns current session context. Production OIDC middleware must replace demo mode.", response: "userId, role, clientId, authenticated, mode." },
  { method: "GET", path: "/api/security/status", purpose: "Reports auth mode, tenant isolation, and destructive-action boundaries.", response: "Security configuration status and required production variables." },
  { method: "GET", path: "/api/capabilities", purpose: "Reports persistence, adapter, AI, security, analytics, testing, and deployment readiness.", response: "Nested capability status object." },
  { method: "GET", path: "/api/incidents?q=power", purpose: "Lists synthetic incidents. q filters ID, title, host, and user.", response: "Incident array." },
  { method: "GET", path: "/api/incidents/INC-1042", purpose: "Returns incident details and configured tools.", response: "Incident object with client and availableTools." },
  { method: "POST", path: "/api/investigations", purpose: "Creates or resumes a durable investigation.", body: '{ "incidentId": "INC-1042" }', response: "investigationId, status, durable steps." },
  { method: "GET", path: "/api/investigations/INC-1042", purpose: "Reads durable case state and initializes it on first access.", response: "Incident, steps, artifacts, evidence, timeline, queries, progress, nextBestAction." },
  { method: "PATCH", path: "/api/investigations/INC-1042/steps", purpose: "Persists one SOP completion state and writes audit/replay events.", body: '{ "stepIndex": 4, "complete": true }', response: "Updated step and persisted: true." },
  { method: "POST", path: "/api/queries/generate", purpose: "Fills a versioned deterministic platform template.", body: '{ "incidentId": "INC-1042", "platform": "Splunk", "indicator": "185.199.110.153", "timeRange": "24 hours" }', response: "Structured query, expected evidence, confidence, templateVersion." },
  { method: "POST", path: "/api/queries/run", purpose: "Stores query execution metadata and returns synthetic normalized events.", body: "Same as /generate.", response: "Query plus status, resultCount, and results." },
  { method: "GET", path: "/api/evidence?incidentId=INC-1042", purpose: "Reads every artifact and provenance field from Prisma.", response: "Evidence array with sourceEventId, collectedAt, confidence, and rawReference." },
  { method: "GET", path: "/api/environment", purpose: "Reads the client and tool enablement from Prisma.", response: "Client, tool records, and availableTools." },
  { method: "POST", path: "/api/environment/save", purpose: "Persists enabled/disabled tool state.", body: '{ "tools": [{ "id": "splunk", "enabled": true }] }', response: "Updated client environment." },
  { method: "GET", path: "/api/dashboard", purpose: "Calculates active, critical, pending evidence, resolved, recent incidents, and audit activity from stored records.", response: "metrics, recent, activity, persistence." },
  { method: "GET", path: "/api/queries", purpose: "Reads generated query history from Prisma.", response: "GeneratedQuery array." },
  { method: "GET", path: "/api/analysis?incidentId=INC-1042", purpose: "Reads the persisted analysis draft and validation records.", response: "Analysis fields and validations." },
  { method: "POST", path: "/api/analysis/save", purpose: "Persists all analyst draft sections and writes replay/audit events.", body: '{ "incidentId": "INC-1042", "summary": "...", "technicalFindings": "...", "scope": "...", "recommendedActions": "..." }', response: "Analysis record and persistence marker." },
  { method: "POST", path: "/api/evidence/collect", purpose: "Reports collected and missing evidence and records an audit event.", body: '{ "incidentId": "INC-1042" }', response: "collected, missing, provenanceIncluded, persistence." },
  { method: "GET", path: "/api/timeline?incidentId=INC-1042", purpose: "Reads normalized events ordered by timestamp.", response: "Timeline event array." },
  { method: "POST", path: "/api/analysis/validate", purpose: "Checks analyst claims against evidence without rewriting input.", body: '{ "incidentId": "INC-1042", "text": "..." }', response: "issues, passed, inputPreserved, persistence." },
  { method: "POST", path: "/api/analysis/proofread", purpose: "Returns security terminology suggestions without applying them.", body: '{ "text": "..." }', response: "suggestions, originalTextPreserved, autoApplied: false." },
  { method: "GET", path: "/api/reports/INC-1042", purpose: "Builds and stores a structured draft report.", response: "Executive summary, timeline, evidence, steps, QA status, recommendations." },
  { method: "POST", path: "/api/handoff", purpose: "Builds a durable-state handoff summary and records the action.", body: '{ "incidentId": "INC-1042", "completedSteps": [0,1,2], "queriesExecuted": 1 }', response: "Completed, pending, findings, missing evidence, next action." },
  { method: "GET", path: "/api/audit?incidentId=INC-1042", purpose: "Reads the investigation flight recorder.", response: "Actor, action, tool, metadata, createdAt." },
  { method: "GET", path: "/api/replay?incidentId=INC-1042", purpose: "Reads chronological analyst/action replay records.", response: "Actor, action, tool, payload, createdAt." },
  { method: "GET", path: "/api/analytics/attack-path", purpose: "Returns observed and inferred graph nodes/edges.", response: "nodes, edges, explanation label." },
  { method: "GET", path: "/api/analytics/blast-radius", purpose: "Returns potential related asset counts and confidence caveat.", response: "users, endpoints, accounts, applications, resources, confidence." },
  { method: "GET", path: "/api/analytics/business-impact", purpose: "Returns potential impact score from asset criticality and data classes.", response: "score, label, caveat." },
  { method: "GET", path: "/api/analytics/soc", purpose: "Returns illustrative SOC performance calculations.", response: "averageMinutes, evidenceCompletion, falsePositiveRate, timeBreakdown." },
  { method: "GET", path: "/api/threat-hunt?indicator=185.199.110.153&type=ip", purpose: "Builds a cross-platform hunt pivot.", response: "Platforms, related assets, confidence, synthetic flag." },
  { method: "GET", path: "/api/openapi", purpose: "Returns the machine-readable API document.", response: "OpenAPI 3.1 JSON." },
  { method: "GET", path: "/api/integrations", purpose: "Lists live integration state without exposing secrets.", response: "Provider, configured flag, and safe status." },
  { method: "POST", path: "/api/integrations/test", purpose: "Validates integration configuration without contacting a vendor in demo mode.", body: '{ "provider": "Splunk", "enabled": true }', response: "connectionAttempted: false until production credentials are configured." },
  { method: "GET", path: "/api/notes", purpose: "Reads durable analyst notes.", response: "Note records with author, incident, body, and timestamps." },
  { method: "POST", path: "/api/notes", purpose: "Creates a durable analyst note and audit record.", body: '{ "incidentId": "INC-1042", "body": "Reviewed destination context." }', response: "Created note." },
  { method: "GET", path: "/api/feedback", purpose: "Reads alert/detection feedback records.", response: "Disposition and analyst feedback records." },
  { method: "POST", path: "/api/feedback", purpose: "Records true-positive, false-positive, duplicate, or usefulness feedback.", body: '{ "incidentId": "INC-1042", "rule": "PS-EXEC-001", "disposition": "FALSE_POSITIVE" }', response: "Created feedback record." },
  { method: "POST", path: "/api/templates/create", purpose: "Creates a persisted custom incident template.", body: '{ "id": "custom-rule", "name": "Custom rule", "description": "..." }', response: "Created IncidentTemplate record." },
  { method: "GET", path: "/api/reports/approvals", purpose: "Reads persisted report review decisions.", response: "Reviewer, decision, comment, and createdAt." },
  { method: "POST", path: "/api/reports/approve", purpose: "Approves a report or requests changes with a reviewer decision.", body: '{ "incidentId": "INC-1042", "decision": "APPROVED", "comment": "Reviewed evidence." }', response: "Persisted approval and updated report status." },
];

const statusRows = [
  ["Prisma persistence", "Working", "API creates and reads investigations, steps, evidence, timeline, queries, analysis, reports, audit, and replay records."],
  ["Vendor integrations", "Mock + fail-closed live contracts", "Mock adapters run synthetic data. Live adapters require tenant base URL, OAuth client, secret storage, scopes, and provider-specific mapping."],
  ["AI providers", "Fallback + provider boundary", "The deterministic provider works now. Live OpenAI, OpenRouter, Ollama, Gemini, and DeepSeek clients still need provider SDK/API configuration and response schemas."],
  ["Authentication / SSO / RBAC", "Permission and tenancy helpers", "Role and tenant checks exist as reusable code. Production IdP, sessions, middleware, provisioning, and policy storage are still deployment work."],
  ["Analytics", "Local engines working", "Attack path, blast radius, business impact, similarity, threat hunting, and SOC calculations work on synthetic inputs. Production requires real telemetry and methodology validation."],
  ["Testing", "Unit/API/accessibility/CI scaffold", "Vitest engine and API contract tests run. Playwright browser/accessibility tests and CI workflow are included; browser execution still requires installed Playwright browsers."],
  ["Operations", "Runbook + readiness endpoints", "Health, readiness, metrics, security status, CI, backup helper, Docker, and operations guidance are included. Provider monitoring and managed backups remain deployment-specific."],
  ["Analyst operations", "Notes, feedback, SLA APIs", "Notes, detection feedback, custom template creation, and audit-derived SLA intervals are persisted. Manager dashboards still need a production analytics methodology and real telemetry."],
  ["Report governance", "Approval workflow", "Reports can be approved, escalated, or returned for changes with a durable reviewer decision. Signed PDF distribution remains deployment-specific."],
  ["Template administration", "Persisted admin page", "The `/templates` page creates persisted custom templates. Versioning, approval promotion, and client-specific overrides remain next governance steps."],
];

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section style={{ borderTop: "1px solid #2a3330", paddingTop: 28, marginTop: 28 }}><h2 style={{ fontSize: 21, margin: "0 0 14px" }}>{title}</h2>{children}</section>; }
function GuideCard({ guide }: { guide: Guide }) { return <article style={{ border: "1px solid #303a36", background: "#171d1a", padding: 16, marginBottom: 9 }}><h3 style={{ margin: "0 0 8px", fontSize: 14, color: "#cfe0d3" }}>{guide.title}</h3><p style={{ margin: "5px 0", color: "#99aaa1", lineHeight: 1.6 }}><b>Purpose:</b> {guide.intent}</p><p style={{ margin: "5px 0", color: "#c7d6cc", lineHeight: 1.6 }}><b>Click:</b> {guide.click}</p><p style={{ margin: "5px 0", color: "#9fc5aa", lineHeight: 1.6 }}><b>What happens:</b> {guide.result}</p>{guide.next && <p style={{ margin: "5px 0", color: "#d0b778", lineHeight: 1.6 }}><b>Next:</b> {guide.next}</p>}</article>; }

export default function DocsPage() {
  return <main style={{ maxWidth: 1180, margin: "0 auto", padding: "42px 24px 80px", fontFamily: "Arial, sans-serif", color: "#d8e1dc", background: "#101315", minHeight: "100vh" }}>
    <Link href="/" style={{ color: "#9dccaa", fontSize: 12 }}>← Back to Nexus</Link>
    <Link href="/operations" style={{ color: "#9dccaa", fontSize: 12, marginLeft: 20 }}>Open Operations Center →</Link>
    <Link href="/templates" style={{ color: "#9dccaa", fontSize: 12, marginLeft: 20 }}>Open Template Admin →</Link>
    <Link href="/approvals" style={{ color: "#9dccaa", fontSize: 12, marginLeft: 20 }}>Open Report Approvals →</Link>
    <Link href="/configuration" style={{ color: "#9dccaa", fontSize: 12, marginLeft: 20 }}>Open Configuration Center →</Link>
    <Link href="/presentation" style={{ color: "#9dccaa", fontSize: 12, marginLeft: 20 }}>Open Hackathon Deck →</Link>
    <p style={{ color: "#92a099", letterSpacing: 2, fontSize: 11, marginTop: 38 }}>OPTIV NEXUS · OPERATOR GUIDE</p>
    <h1 style={{ fontSize: 36, margin: "10px 0" }}>How every control works</h1>
    <p style={{ maxWidth: 820, color: "#9ca9a2", lineHeight: 1.8 }}>This is the click-by-click operating manual for the Nexus workspace. Each entry below states why a control exists, exactly what to click, what the application changes, what is persisted, and what should happen next.</p>
    <div style={{ display: "flex", flexWrap: "wrap", gap: 7, margin: "24px 0" }}>{["Alert", "Investigation", "SOP", "Query", "Evidence", "Timeline", "QA", "Report"].map((x, i) => <span key={x} style={{ border: "1px solid #40564a", color: "#a9d2b4", background: "#1b2820", padding: "8px 10px", fontSize: 11 }}>{i + 1}. {x}</span>)}</div>
    <Section title="Start here: the complete demo flow"><ol style={{ color: "#aab5af", lineHeight: 2 }}><li>Open Overview and click the `INC-1042` incident row.</li><li>Click Start / resume. This creates the case records in SQLite.</li><li>Open Investigation and click pending step circles to record progress.</li><li>Open Queries, choose a configured platform, set the indicator, and run the mock query.</li><li>Open Evidence to inspect provenance and unresolved artifacts.</li><li>Open Timeline and select events to inspect source context.</li><li>Open Analysis, deliberately review the mismatch warning, then apply or keep a value explicitly.</li><li>Open Report, copy or print the report, and generate a handoff for the next analyst.</li><li>Open Progress & Roadmap to see which functionality is demo-ready and which needs production infrastructure.</li></ol></Section>
    <Section title="Every UI action"><div>{guides.map(guide => <GuideCard key={guide.title} guide={guide} />)}</div></Section>
    <Section title="API endpoint reference"><p style={{ color: "#aab5af", lineHeight: 1.7 }}>All JSON mutation bodies are validated with Zod. GET investigation/evidence/report routes may initialize the case if it does not exist. Mutations write audit/replay records where stated. Mock responses are intentionally labeled and never claim a live vendor action.</p>{endpoints.map(endpoint => <article key={endpoint.path + endpoint.method} style={{ borderTop: "1px solid #2a3330", padding: "14px 0", display: "grid", gridTemplateColumns: "65px minmax(260px, .9fr) 1.2fr", gap: 12, fontSize: 12 }}><b style={{ color: endpoint.method === "GET" ? "#9dccaa" : "#dec17d" }}>{endpoint.method}</b><div><code style={{ color: "#dbe6de" }}>{endpoint.path}</code>{endpoint.body && <pre style={{ whiteSpace: "pre-wrap", color: "#a8c9af", background: "#0b0f10", padding: 8, margin: "8px 0 0" }}>{endpoint.body}</pre>}</div><div style={{ color: "#a0aea6", lineHeight: 1.6 }}><b style={{ color: "#c6d6ca" }}>{endpoint.purpose}</b><br />Returns: {endpoint.response}</div></article>)}</Section>
    <Section title="Architecture and data flow"><p style={{ color: "#aab5af", lineHeight: 1.8 }}>Nexus is organized around a deterministic investigation core. Incident templates define safe steps and query templates. The client environment filters those steps to configured tools. Adapters normalize tool results into evidence. Prisma stores the investigation state. Analytics operates on normalized records. AI providers can enrich the process but the fallback path remains usable without external AI.</p><pre style={{ background: "#0b0f10", border: "1px solid #303a36", padding: 16, overflow: "auto", color: "#aed2b8", lineHeight: 1.7 }}>{`Alert\n  -> Incident template + client environment\n  -> Investigation steps + required artifacts\n  -> Adapter search / host / user / network\n  -> Normalized evidence + provenance\n  -> Timeline + analytics + next best action\n  -> Analyst analysis + deterministic QA\n  -> Report + handoff + audit/replay`}</pre></Section>
    <Section title="What is complete and what is pending"><div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}><thead><tr style={{ textAlign: "left", color: "#899790" }}><th style={{ padding: 10 }}>Area</th><th style={{ padding: 10 }}>Status</th><th style={{ padding: 10 }}>Explanation</th></tr></thead><tbody>{statusRows.map(row => <tr key={row[0]} style={{ borderTop: "1px solid #2a3330" }}>{row.map((cell, i) => <td key={cell} style={{ padding: 10, color: i === 1 ? "#a9d4b3" : "#aab5af", verticalAlign: "top", lineHeight: 1.6 }}>{cell}</td>)}</tr>)}</tbody></table></div></Section>
    <Section title="Local setup and operating safeguards"><pre style={{ background: "#0b0f10", border: "1px solid #303a36", padding: 16, overflow: "auto", color: "#aed2b8" }}>{`npm install\ncopy .env.example .env\nnpm run db:generate\nnpm run db:push\nnpm run db:seed\nnpm run dev\n\n# unit/engine tests\nnpm test\n\n# browser smoke tests\nnpx playwright install chromium\nnpm run test:e2e`}</pre><p style={{ color: "#aab5af", lineHeight: 1.8 }}>Live integrations fail closed when OAuth configuration is missing. No connector isolates endpoints, disables accounts, blocks IPs, or changes credentials. AI output must remain reviewable and evidence-backed. Production requires real secrets management, reviewed database migrations, authenticated tenants, backups, monitoring, and human approval workflows.</p></Section>
    <Section title="Operations and recovery"><p style={{ color: "#aab5af", lineHeight: 1.8 }}>Use `/api/ready` for load-balancer readiness, `/api/metrics` for persisted counters, and `/api/security/status` to verify whether the process is still in demo session mode. The repository includes `.github/workflows/ci.yml`, `ops/README.md`, migration guidance, and `scripts/backup-database.ps1`. These are executable local/CI safeguards; production PostgreSQL backups, secret management, OIDC, and observability must be connected to the chosen hosting provider.</p></Section>
  </main>;
}
