"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function OperationsPage() {
  const [data, setData] = useState<any>({ notes: [], feedback: [], sla: {}, audit: [], replay: [] });
  const [note, setNote] = useState("");
  const [disposition, setDisposition] = useState("USEFUL");
  const [message, setMessage] = useState("");
  const load = () => Promise.all([fetch("/api/notes").then(r => r.json()), fetch("/api/feedback").then(r => r.json()), fetch("/api/analytics/sla").then(r => r.json()), fetch("/api/audit?incidentId=INC-1042").then(r => r.json()), fetch("/api/replay?incidentId=INC-1042").then(r => r.json())]).then(([notes, feedback, sla, audit, replay]) => setData({ notes, feedback, sla, audit, replay }));
  useEffect(() => { load().catch(() => setMessage("Unable to load operations data")); }, []);
  async function saveNote() { const response = await fetch("/api/notes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ incidentId: "INC-1042", body: note }) }); setMessage(response.ok ? "Note persisted" : "Note failed"); if (response.ok) { setNote(""); load(); } }
  async function saveFeedback() { const response = await fetch("/api/feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ incidentId: "INC-1042", rule: "PS-EXEC-001", disposition }) }); setMessage(response.ok ? "Feedback persisted" : "Feedback failed"); if (response.ok) load(); }
  return <main className="ops-page"><div className="ops-shell"><Link href="/" className="ops-back">← Back to Nexus</Link><div className="eyebrow">NEXUS OPERATIONS CENTER</div><h1>Analyst operations</h1><p className="ops-intro">Durable notes, detection feedback, SLA measurement, audit trail, and investigation replay for ACME Financial.</p><div className="ops-grid metrics">{[["NOTES",data.notes.length,"Persisted analyst notes"],["FEEDBACK",data.feedback.length,"Detection dispositions"],["SLA CASES",data.sla.measuredCases??0,"Audit-derived measurements"],["REPLAY EVENTS",data.replay.length,"Chronological case actions"]].map(item=><div className="ops-card" key={item[0]}><small>{item[0]}</small><strong>{item[1]}</strong><span>{item[2]}</span></div>)}</div><div className="ops-grid two"><section className="ops-card"><h2>Analyst notes</h2><p>Notes are stored in Prisma and attached to the client workspace.</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add an investigation observation..."/><button onClick={saveNote}>Save note</button><div className="ops-list">{data.notes.map((item:any)=><div key={item.id}><b>{item.authorId}</b><span>{item.body}</span><small>{new Date(item.createdAt).toLocaleString()}</small></div>)}</div></section><section className="ops-card"><h2>Detection feedback</h2><p>Record whether a detection was useful for future rule tuning.</p><select value={disposition} onChange={e=>setDisposition(e.target.value)}><option>USEFUL</option><option>NOT_USEFUL</option><option>TRUE_POSITIVE</option><option>FALSE_POSITIVE</option><option>DUPLICATE</option></select><button onClick={saveFeedback}>Submit feedback</button><div className="ops-list">{data.feedback.map((item:any)=><div key={item.id}><b>{item.rule} · {item.disposition}</b><span>{item.reason ?? "No reason supplied"}</span><small>{new Date(item.createdAt).toLocaleString()}</small></div>)}</div></section></div><div className="ops-grid two"><section className="ops-card"><h2>SLA intelligence</h2><p>Calculated from Nexus audit timestamps. Vendor-side time is excluded.</p><div className="ops-facts"><span>Target <b>{data.sla.targetMinutes ?? 30} minutes</b></span><span>Measured cases <b>{data.sla.measuredCases ?? 0}</b></span></div><div className="ops-callout">{data.sla.caveat ?? "No SLA measurements available."}</div></section><section className="ops-card"><h2>Flight recorder</h2><p>Audit and replay actions for `INC-1042`.</p><div className="ops-list">{[...data.audit.map((item:any)=>({...item,kind:"AUDIT"})),...data.replay.map((item:any)=>({...item,kind:"REPLAY"}))].slice(-10).reverse().map((item:any)=><div key={`${item.kind}-${item.id}`}><b>{item.kind} · {item.action}</b><span>{item.actor ?? "system"}</span><small>{new Date(item.createdAt).toLocaleString()}</small></div>)}</div></section></div>{message&&<div className="ops-message">{message}</div>}</div></main>;
}
