"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function ConfigurationPage(){
  const [data,setData]=useState<any>(null),[message,setMessage]=useState("");
  useEffect(()=>{Promise.all([fetch("/api/capabilities").then(r=>r.json()),fetch("/api/security/status").then(r=>r.json()),fetch("/api/ready").then(r=>r.json()),fetch("/api/metrics").then(r=>r.json())]).then(([capabilities,security,ready,metrics])=>setData({capabilities,security,ready,metrics})).catch(()=>setMessage("Unable to load configuration status"))},[]);
  const cap=data?.capabilities;
  return <main className="ops-page"><div className="ops-shell"><Link href="/" className="ops-back">← Back to Nexus</Link><div className="eyebrow">NEXUS CONFIGURATION CENTER</div><h1>Providers, integrations, and readiness</h1><p className="ops-intro">This page shows what is configured, what is safe to run locally, and which production values must be supplied before external systems can be contacted.</p>{message&&<div className="ops-message">{message}</div>}<div className="ops-grid metrics"><div className="ops-card"><small>DATABASE</small><strong>{data?.ready?.database??"Loading"}</strong><span>Readiness: {data?.ready?.status??"pending"}</span></div><div className="ops-card"><small>AUTH MODE</small><strong>{data?.security?.authMode??"Loading"}</strong><span>Session: {data?.security?.sessionProvider??"pending"}</span></div><div className="ops-card"><small>AI FALLBACK</small><strong>{cap?.ai?.deterministicFallback?"Active":"Unknown"}</strong><span>Safe without provider keys</span></div><div className="ops-card"><small>DATABASE RECORDS</small><strong>{data?.metrics?.investigations??"—"}</strong><span>Persisted investigations</span></div></div><section className="ops-card"><h2>Security integrations</h2><p>Mock adapters are available now. Live transport remains disabled until server-side credentials and provider mappings are supplied.</p><div className="ops-table">{cap?.adapters?.live?.map((item:any)=><div key={item.name}><b>{item.name}</b><span>{item.status}</span><small>{item.configured?"Configured boundary":"Credentials required"}</small></div>)}</div></section><section className="ops-card"><h2>AI providers</h2><p>Provider selection is environment-driven. The deterministic fallback remains active when endpoint and key values are absent.</p><div className="ops-table">{cap?.ai?.liveProviders?.map((item:any)=><div key={item.provider}><b>{item.provider}</b><span>{item.status}</span><small>{item.configured?"HTTP boundary configured":"Credentials required"}</small></div>)}</div></section><section className="ops-card"><h2>Production checklist</h2><div className="ops-list">{[["OIDC authentication",Boolean(data?.security?.sessionProvider==="oidc-configured"),"Set OIDC_ISSUER, OIDC_CLIENT_ID, and OIDC_CLIENT_SECRET"],["Database readiness",data?.ready?.database==="ok","Use reviewed migrations before production"],["Tenant isolation",Boolean(data?.security?.tenantIsolation),"Apply tenant scope to every authenticated query"],["Destructive response",false,"Remains disabled until a separate approval service exists"],["Observability",false,"Connect structured logs, traces, metrics, and alerts"],["Backups",false,"Use managed encrypted PostgreSQL backups and restore drills"]].map(item=><div key={String(item[0])}><b>{item[1]?"READY":"PENDING"} · {item[0]}</b><span>{item[2]}</span></div>)}</div></section><p className="ops-footnote">No secrets are displayed or accepted by this browser page. Use a server-side secret manager for production configuration.</p></div></main>;
}
